### ISSUE TITLE
README.md gramatical advice

### ISSUE THREAD

**Issue by junho1185** [ByteAurora/ByteAurora#1]
https://github.com/ByteAurora/ByteAurora/blob/738a0bcbcc19aa6e7c6917f957b9a6264e3e4cd6/README.md?plain=1#L8

`Experienced with ~ ` sounds un-natural. I recommend you to try using `Experiences with~` or just `Experienced ~`.

**Comment by ByteAurora** [comment]
수정했습니다 :)
